function [axpos] = pdffigure(width)
% Define figure for report
% Save to eps-image

rg = 1/((1+sqrt(5))/2);

axpos =   [ 10 10 80 80]/100;
w=14;

switch width
 case 1,  r = rg;
 case 2,  r = 0.4;
 case 31, r = 1.2;
 case 21, r = 0.8;
 case 11, r = 1;
 case 5,  r =1/sqrt(2); 
 case 6,  r =sqrt(2); 
    
end

set (gcf, ...
   'DefaultAxesFontName',   'Times', ...
   'DefaultTextFontName',   'Times',...
   'DefaultAxesFontSize',   14, ...
   'DefaultTextFontSize',   14, ...
   'DefaultAxesFontWeight', 'Normal', ...
   'DefaultAxesLineWidth',  0.5, ...
   'DefaultLineLineWidth',  0.5, ...
   'DefaultLineMarkerSize', 8, ...
   'Units',                 'centimeters', ...
   'PaperUnits',            'centimeters', ...
   'PaperOrientation',      'portrait', ...
   'PaperPosition',         [ 0.05*w*[1 r] 0.9*w*[1 r] ], ...
   'PaperSize',             [w*[1 r]], ...
   'DefaultAxesPosition',   axpos, ...
   'InvertHardcopy',        'on' );
   %'Position',              [ 0 0 w*[1 r] ], ...
   

return   






